### ISSUE TITLE
HOW TO FIX SSL ERROR

### ISSUE THREAD

**Issue by SirFuzzo** [Alucard-Selfbot/Alucard-Selfbot-src#10]
If youre getting an SSL error, update discord.py. if they havent updated it or you still get an SSL CERTIFICATE ERROR:

1.Open chrome
2.Go to Discord.com
3.Click the lock icon next to the url to view the certificate info
4.Click the details tab
5.Press next till it asks you where to save the file.
6.Save the file
7.Browse to location of the certificate you exported for discord.com
8.Right click it
9.Press install certificate

Windows users only obv

dm me on discord Defonicx#1337 if this helped you. dont dm me if you cant figure out how to set up the bot. it works fine. I had to make some source code changes but it may have to do with the version of python I chose. Unless the author through some tiny wrenches in to ward of skids ;)

**Comment by SirFuzzo** [comment]
Oh ill keep it open for now

**Comment by SirFuzzo** [comment]
I'll reopen this for anyone that needs it unless the author decides otherwise.

**Comment by Fweak** [comment]
:D Thanks!
