### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by nosleep2242** [Alucard-Selfbot/Alucard-Selfbot-src#12]
Tried to follow the last post to fix it but theres no "next" button in certificates for me. Is there any other way to fix this error?

**Comment by mlucap** [comment]
On Chrome you need to click the lock, then Certificate (valid), Details - should be the second option on the top, Copy to File..., click next a few times until it asks you where you want to save it to and give it any name ie. Discord, then right click the certificate where you saved it to and click Install Certificate, then click next until it successfully installs.

**Comment by SirFuzzo** [comment]
Isnt this literally what my post said thats myseriously gone now? lmao
