### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by lolsaiv** [Alucard-Selfbot/Alucard-Selfbot-src#15]
everytime i run the program (main or launch) it brings up errors, i have reinstalled it multiple times and it still doesnt work.

**Comment by Fweak** [comment]
What's the error. Could provide info atleast!

**Comment by anthony5000** [comment]
> everytime i run the program (main or launch) it brings up errors, i have reinstalled it multiple times and it still doesnt work.

Ran into the same problem. Here are some screenshots.

https://prnt.sc/tnj8p0
https///prnt.sc/tnj93t

**Comment by Fweak** [comment]
Yeah that's an issue on discord.py end. You can fix it by updating: 
python -m pip install -U discord.py
