### ISSUE TITLE
Wont Launch

### ISSUE THREAD

**Issue by CrawlerCrusher** [Alucard-Selfbot/Alucard-Selfbot-src#18]
Traceback (most recent call last):
  File "Main.py", line 1904, in <module>
    Init()
  File "Main.py", line 169, in Init
    Alucard.run(token, bot=False, reconnect=True)

**Comment by SirFuzzo** [comment]
I'm having the same issue. Unfortunately, I'm not well versed enough in Python to fix it.

Devs if you read this I'd happily donate for a commit to address this issue or even a good hint on how to do it ourselves ;)

**Comment by SirFuzzo** [comment]
I'ved fixed it. Pretty sure I'm running python 3.8.x. and I opened main.py in sublimetext (you can use notepad.) very near the top you will see "import discord, etc, etc". The line below also has a list of imports. Those are what they put requirements.txt. I litereally added all of them to requirements.txt. Also I modified installer.bat 4th line to be "pip3 install -r requirements.txt". If pip3 has a PATH, it should use python3 to install the requirements. I got 3~ so 

Running install.bat I got a few errors (functools), but every time I got an error on a specific item I deleted it from requirements.txt and re-ran it. After doing that for a while my requirements.txt looked like:

datetime
asyncio
discord.py
colorama
numpy
requests
aiohttp
bs4
pymongo
selenium
pyPrivnote
gtts
dnspython
image

And it worked. If you have the littlest knowledge of python you should be able to fix this. Especially given that I explained exactly what I did to fix it.

Note I'm no python pro and there was probably a much quicker way to do it, I had to resort to brute forcing a result.

 Defonicx#1337 dm for 𝕔𝕧𝕧, 𝕗𝕦𝕝𝕝𝕤, 𝕤𝕤𝕟'𝕤, 𝕚𝕟𝕕𝕚𝕧𝕚𝕕𝕦𝕒𝕝 𝕣𝕖𝕤𝕚𝕕𝕖𝕟𝕥𝕚𝕒𝕝 𝕡𝕣𝕠𝕩𝕚𝕖𝕤 𝕒𝕟𝕪𝕨𝕙𝕖𝕣𝕖 𝕚𝕟 𝕨𝕠𝕣𝕝𝕕
