### ISSUE TITLE
No module named stringhelper

### ISSUE THREAD

**Issue by Shukla-G** [Alucard-Selfbot/Alucard-Selfbot-src#21]
Getting this error
 
Traceback (most recent call last):
  File "Main.py", line 13, in <module>
    from stringhelper.stringhelper import String
ModuleNotFoundError: No module named 'stringhelper'
RIP I don't want to make a loop for a user who doesn't want to understand :)
Press any key to continue . . .

Tried pip install stringhelper but it cannot find it

Collecting stringhelper
  ERROR: Could not find a version that satisfies the requirement stringhelper (from versions: none)
ERROR: No matching distribution found for stringhelper

**Comment by Fweak** [comment]
Resolve the issue: something happened with the package so we had to remake it. Should be working now
`pip install stringhelper`
