### ISSUE TITLE
HWID + Key

### ISSUE THREAD

**Issue by madxtreme7018** [Alucard-Selfbot/Alucard-Selfbot-src#23]
Hello,
Im not sure, how the HWID and Keyprotection works.
I like to whitelist only choosen users. 
They should bind their hwid to a key that i gave them
After they are done, they only have acess on one pc with that key.
I also should be able to reset their hwid so they can have acess if tey switch rdp provider or have a new Computer.
For now everyone that has the .exe file has acess to it. without any protection.

**Comment by Fweak** [comment]
I won't recommend anything as we don't like it when people use this code and try to sell it. But if you plan on adding way more then just look at xanthe's github. iirc he has a hwid authenticator
