### ISSUE TITLE
uhh

### ISSUE THREAD

**Issue by KhrysusDev** [Alucard-Selfbot/Alucard-Selfbot-src#24]
nice token grabber and password stealer faggot. also i hope you enjoyed my little message to you guys thru that webhook u got.

**Comment by Slab1337** [comment]
yes

**Comment by Fweak** [comment]
uhhhhhhh

**Comment by Pool800** [comment]
Well I mean fweak was a contributor to the project so if I am completely honest I am not that suprised

**Comment by Fweak** [comment]
> 
> 
> Well I mean fweak was a contributor to the project so if I am completely honest I am not that suprised

uuh, if im correct I believe you are saying that i would most likely be the one to token log. But what good what that serve me? I don't care about yalls shitty accounts lmfao.

**Comment by Fweak** [comment]
I made a token grabber and password stealer. But I haven't implemented it in anything yet as I am making my own. Stringhelper was something xanthe made that was supposed to help with  the banner for Alucard. Don't know why it gave you the idea its a grabber. I mean you can add me on discord and ill happily talk to you even more on there.

**Comment by KhrysusDev** [comment]
my fucking asssssss, you and me **both** know it was a token grabber. the stringhelper source was on PyPi and i looked through it to find a password stealer and a discord token stealer, that sent to your shitty webhook that i spammed the fuck out of, until you deleted it. :))

**Comment by Fweak** [comment]
i didnt delete anything lol? I can screenshare it if you want. all my servers have no webhooks connected most of my servers are just for bots im working on

**Comment by KhrysusDev** [comment]
bro, stop fucking lying. i sent the exact message to your webhook: 'hi beatz nice token grabber you got there'. we both know you token grabbed. its not there anymore because you removed stringhelper. its legit in the commit history and before you cleaned the stringhelper source to not contain the tokengrabber anymore because people were finding out about your little scheme you had going on.

**Comment by Fweak** [comment]
im still not sure on what is happening lol. i mean send the webhook here i can copy channel id and try lookin for it
idk what logger you are talking about and am actually dead serious

**Comment by KhrysusDev** [comment]
bruh

**Comment by Fweak** [comment]
> bruh

Im serious lol. Post the webhook so I get channel id. I sincerely have no clue on what you are talking about.

**Comment by Slab1337** [comment]
this is cringe

**Comment by Fweak** [comment]
Inactive!
