### ISSUE TITLE
AttributeError: module 'ctypes' has no attribute 'windll'

### ISSUE THREAD

**Issue by Wh7sk** [Alucard-Selfbot/Alucard-Selfbot-src#25]
`
Traceback (most recent call last):
  File "Main.py", line 25, in <module>
    ctypes.windll.kernel32.SetConsoleTitleW(f'[Alucard Selfbot v{SELFBOT.__version__}] | Loading...')
AttributeError: module 'ctypes' has no attribute 'windll'
`

Tried to use on a debain system. Ubuntu 16.04.7 LTS
Same error with python3.5 python3.7 python3.8.

**Comment by Fweak** [comment]
windll basically means a windows dll (simpler terms that is). So im guessing Ubuntu doesn't have the dll that is required so it wont work. 
If you want to use alucard you can manually remove all the times ctype.windll is required and see if that works.
