### ISSUE TITLE
No such file or directory: 'Data/Tokens/user-tokens.txt'

### ISSUE THREAD

**Issue by Cliv69** [Alucard-Selfbot/Alucard-Selfbot-src#26]
[ERROR]: Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: 'Data/Tokens/user-tokens.txt'

There is no file I tried making one in the folder help thanks

**Comment by bPou** [comment]
create a folder and the user-tokens.txt

**Comment by RealExcess72** [comment]
I think you should make a file called user-tokens.txt
