### ISSUE TITLE
[ERROR]: Member "<@>" not found.

### ISSUE THREAD

**Issue by Wh7sk** [Alucard-Selfbot/Alucard-Selfbot-src#28]
discord.Member
user.mention

I have no idea why it's not tag.
I am friends with the person.

**Comment by maybepiffpuffas** [comment]
It's because bots only work in servers and the api doesn't allow mentions in dms. The command will work on servers tho.

**Comment by Wh7sk** [comment]
> It's because bots only work in servers and the api doesn't allow mentions in dms. The command will work on servers tho.

That's actually incorrect, the version (modified) I have let's you use mention them. I'm not sure what is causing not allowing it mention.

**Comment by maybepiffpuffas** [comment]
> > It's because bots only work in servers and the api doesn't allow mentions in dms. The command will work on servers tho.
> 
> That's actually incorrect, the version (modified) I have let's you use mention them. I'm not sure what is causing not allowing it mention.

I saw the explanation in the discord.py github issues, I don't really know why.

**Comment by iiTrauma** [comment]
change the `discord.Member` to `discord.User` in all lines ( you can use a tool or text editor )

**Comment by Fweak** [comment]
Yeah when mentioning someone in a server Discord.py checks it and then creates a Member object for it.
Else if not in a server then it creates a User
