### ISSUE TITLE
NSFW commands not working

### ISSUE THREAD

**Issue by diamondoreboi** [Alucard-Selfbot/Alucard-Selfbot-src#29]
command prompt doesn't show any errors either, any fix?

**Comment by sla-b** [comment]
https://pornhub.com

**Comment by ResolutePSD** [comment]
down bad

**Comment by AzgarDev** [comment]
NSFW commands uses an API. At the time you were testing the NSFW commands the API was probally down.

**Comment by Fweak** [comment]
> NSFW commands uses an API. At the time you were testing the NSFW commands the API was probally down.

Yes this is pretty common! Please retry the commands and let me know if there's anything else.

**Comment by HideakiAtsuyo** [comment]
https://github.com/Alucard-Selfbot/Alucard-Selfbot-src/commit/19b621b05e282e687406fbbc53a9d37af0d8f3b9
