### ISSUE TITLE
error when launching on repl.it

### ISSUE THREAD

**Issue by JpbmOfficial** [Alucard-Selfbot/Alucard-Selfbot-src#33]
'run' isn't configured in the .replit file
try adding 'run = "echo hello word"' to .replit
---------------------------------------------------------------
what do  I do to fix it in repl.it?

**Comment by Fweak** [comment]
Reconfigured the `.replit` file on the project.
The error was pointing out that there was no arguments (or startup commands) for **`run`**.

Fixed it by adding: `run = "python3 Main.py"`

**Comment by JpbmOfficial** [comment]
Thank you! Also, another question, how can I solve the windll not found problem? I don't know  how to delete some parts of the ctype.windll so that the bot work

**Comment by iiTrauma** [comment]
ctrl + f and search all lines which contain `ctype`

**Comment by JpbmOfficial** [comment]
> ctrl + f and search all lines which contain `ctype`

I did that, but, for example, when I delete the first one containing ctype.windll.kernel32.... , when i try to run the bot, it doesnt run

**Comment by Fweak** [comment]
Mind showing a screenshot of the error **remove any important details**? 
Also make sure to delete the whole line that contains windll not just the word :D

**Comment by JpbmOfficial** [comment]
I think I solved the windll part for now, but now another error pops up:
```
Traceback (most recent call last):
  File "Main.py", line 45, in <module>
    hwid = subprocess.check_output('wmic csproduct get uuid').decode().split(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1706, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'wmic csproduct get uuid'
exit status 1
```

**Comment by Gowixx** [comment]
remove line 45

**Comment by RBaller0875** [comment]
nothing happens when i try to run it

**Comment by 01rih** [comment]
i have this error

python3 Main.py
Traceback (most recent call last):
  File "Main.py", line 48, in <module>
    hwid = subprocess.check_output('wmic csproduct get uuid').decode().split('\n')[1].strip()
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'wmic csproduct get uuid'
exit status 1

**Comment by Gowixx** [comment]
remove the line hwid = subprocess.check_output('wmic csproduct get uuid').decode().split('\n')[1].strip()

**Comment by RingingDaddy** [comment]
my repl always says "fails to connect, retrying" everytim i put alucard in repl is there anything else i can host on

**Comment by Fweak** [comment]
> my repl always says "fails to connect, retrying" everytime i put alucard in repl is there anything else i can host on

I would attempt to purchase a vps (Virtual Private Server) for hosting of this!

**Comment by HideakiAtsuyo** [comment]
https://github.com/Alucard-Selfbot/Alucard-Selfbot-src/commit/19b621b05e282e687406fbbc53a9d37af0d8f3b9
