### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by chayse6969** [Alucard-Selfbot/Alucard-Selfbot-src#34]
python3 Main.py
Traceback (most recent call last):
  File "Main.py", line 6, in <module>
    import urllib.parse, urllib.request, re, json, requests, webbrowser, aiohttp, dns.name, asyncio, functools, logging
ModuleNotFoundError: No module named 'dns'

please help me

**Comment by Fweak** [comment]
`pip install dnspython`
[Module It's Referering](https://pypi.org/project/dnspython/)

**Comment by ciprus0** [comment]
Double click install then double click launch, if you do that then you won't need to do 'pip install' at all, and also if you get an error it will probably be a bunch of red lines. in that cause you will need to install C++ build tools

**Comment by Fweak** [comment]
> Double click install then double click launch, if you do that then you won't need to do 'pip install' at all, and also if you get an error it will probably be a bunch of red lines. in that cause you will need to install C++ build tools

Thanks for the tip!
