### ISSUE TITLE
nevermind I found the fix, you need to put your password in the config.json folder for it to work.

### ISSUE THREAD

**Issue by bg-181** [Alucard-Selfbot/Alucard-Selfbot-src#35]
nevermind I found the fix, you need to put your password in the config.json folder for it to work.

_Originally posted by @ciprus0 in https://github.com/AlucardSB/Alucard-Selfbot-src/issues/30#issuecomment-800723219_

Still doesn't work for me.

**Comment by HideakiAtsuyo** [comment]
https://github.com/Alucard-Selfbot/Alucard-Selfbot-src/commit/19b621b05e282e687406fbbc53a9d37af0d8f3b9
