### ISSUE TITLE
Linux error

### ISSUE THREAD

**Issue by ClemGlacee** [Alucard-Selfbot/Alucard-Selfbot-src#36]
Launching "`python Main.py`" in the terminal outputs this:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/sadsoup/Github/Alucard-Selfbot-src/Main.py", line 25, in <module>
    ctypes.windll.kernel32.SetConsoleTitleW(f'[Alucard Selfbot v{SELFBOT.__version__}] | Loading...')
AttributeError: module 'ctypes' has no attribute 'windll'
```
I had to comment some features like hwid and then it started

**Comment by HarryTq** [comment]
Just remove that call and it will work on Linux, that's a WinApi call hence why it won't work on any non Windows systems

**Comment by Fweak** [comment]
Yup! It's been an issue that we had for a bit but since we stopped development I would jt say its best if you or someone remove it and jut use it without it.

**Comment by HideakiAtsuyo** [comment]
https://github.com/Alucard-Selfbot/Alucard-Selfbot-src/commit/19b621b05e282e687406fbbc53a9d37af0d8f3b9
