### ISSUE TITLE
Dms and some other features are not working

### ISSUE THREAD

**Issue by ClemGlacee** [Alucard-Selfbot/Alucard-Selfbot-src#37]
using the `dm` or `dmall` command does not work neither does `masscon` or `masslogin`

**Comment by Fweak** [comment]
> using the `dm` or `dmall` command does not work neither does `masscon` or `masslogin`

Discord & Discord.Py have removed features on Selfbotting and that coming with GuildMemberCaches.
Since Discord is now requiring intents for a load of things this is probably the reason why.
