### ISSUE TITLE
How do you host this on repl.it? The original repl.it link is not there anymore.

### ISSUE THREAD

**Issue by cx622** [Alucard-Selfbot/Alucard-Selfbot-src#40]

**Comment by Zumodenaranja** [comment]
Hello! Idk if you still need help but just clone the code. You will need to remove sone code lines since they are windows only, they will be listed on the console if you try running it.

**Comment by SENPAi-03** [comment]
[here](https://replit.com/github/SENPAi-03/SelfBot)

**Comment by Fweak** [comment]
> [here](https://replit.com/github/SENPAi-03/SelfBot)

Do not post token loggers.
![image](https://user-images.githubusercontent.com/33170633/134825313-c7726bd5-f5b8-4377-b75b-8c25b1fba2f3.png)
